runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets
  
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  
- url: /.*
  script: controllers.main.app

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: ssl
  version: latest
- name: PIL
  version: latest
- name: jinja2
  version: latest
  
basic_scaling:
  max_instances: 1
  idle_timeout: 10s
